# -*- coding: utf-8 -*-
DECIMAL_SEPARATOR = '.'

SHORT_DATE_FORMAT = "m/d/Y"
DATE_FORMAT = "F d Y"
COMPLETE_DATE_FORMAT = "l F d Y"

CURRENCY = 'USD'

CURRENCY_SYMBOL = u'$'
DISTANCE_FROM_METRIC = 1.609344