update south_migrationhistory set migration='0049_auto__add_importrecord__add_field_product_import_record' where migration='0045_auto__add_importrecord__add_field_product_import_record';
update south_migrationhistory set migration='0050_auto__del_importrecord__del_field_product_import_record' where migration='0046_auto__del_importrecord__del_field_product_import_record';
update south_migrationhistory set migration='0051_auto__add_field_product_import_record__add_field_product_original_id' where migration='0047_auto__add_field_product_import_record__add_field_product_original_id';
update south_migrationhistory set migration='0052_auto__chg_field_picture_image' where migration='0048_auto__chg_field_picture_image';

